export const data = [
    {
        Name: "Amy",
        Email: "ipsum@parturientmontesnascetur.org",
        Date: "11/12/2020",
        Country: "Togo",
        "Pin code": "4524",
    },
    {
        Name: "Danielle",
        Email: "ipsum.primis@lectuspede.net",
        Date: "09/18/2020",
        Country: "Mexico",
        "Pin code": "4017",
    },
    {
        Name: "Jillian",
        Email: "eu@Phasellusliberomauris.ca",
        Date: "05/08/2020",
        Country: "Micronesia",
        "Pin code": "7157",
    },
    {
        Name: "Noelle",
        Email: "aliquam.eros@Sedet.ca",
        Date: "04/21/2021",
        Country: "Jersey",
        "Pin code": "8003",
    },
    {
        Name: "Mara",
        Email: "montes.nascetur@cursus.edu",
        Date: "10/15/2020",
        Country: "Latvia",
        "Pin code": "6596",
    },
    {
        Name: "Zachary",
        Email: "Donec@consectetuercursuset.edu",
        Date: "03/30/2021",
        Country: "Korea, South",
        "Pin code": "7002",
    },
    {
        Name: "Odette",
        Email: "Sed.id.risus@ametconsectetueradipiscing.ca",
        Date: "04/08/2020",
        Country: "Libya",
        "Pin code": "7243",
    },
    {
        Name: "Dakota",
        Email: "risus.a@Nunclectus.net",
        Date: "01/08/2021",
        Country: "Aruba",
        "Pin code": "6674",
    },
    {
        Name: "Lana",
        Email: "Duis@eros.com",
        Date: "06/03/2021",
        Country: "Greece",
        "Pin code": "4513",
    },
    {
        Name: "Zane",
        Email: "sed.est.Nunc@mattisvelit.org",
        Date: "08/25/2021",
        Country: "Hong Kong",
        "Pin code": "6012",
    },
    {
        Name: "Grace",
        Email: "vulputate.dui.nec@laciniaorci.org",
        Date: "09/28/2021",
        Country: "Falkland Islands",
        "Pin code": "8182",
    },
    {
        Name: "Martena",
        Email: "malesuada.fringilla@magnisdisparturient.co.uk",
        Date: "12/24/2020",
        Country: "Bermuda",
        "Pin code": "6699",
    },
    {
        Name: "Imogene",
        Email: "quam.quis@magna.ca",
        Date: "12/07/2021",
        Country: "Tanzania",
        "Pin code": "1261",
    },
    {
        Name: "Martina",
        Email: "tincidunt.neque@torquentper.net",
        Date: "07/21/2020",
        Country: "Maldives",
        "Pin code": "9784",
    },
    {
        Name: "Craig",
        Email: "commodo@Quisqueimperdieterat.edu",
        Date: "05/25/2020",
        Country: "Tonga",
        "Pin code": "8594",
    },
    {
        Name: "Igor",
        Email: "egestas.ligula@ultricesposuerecubilia.org",
        Date: "07/17/2021",
        Country: "Tuvalu",
        "Pin code": "8808",
    },
    {
        Name: "Amelia",
        Email: "Aenean@montesnascetur.co.uk",
        Date: "08/14/2021",
        Country: "Guadeloupe",
        "Pin code": "6703",
    },
    {
        Name: "Abbot",
        Email: "Morbi.neque@nullaCraseu.com",
        Date: "03/25/2021",
        Country: "Philippines",
        "Pin code": "9615",
    },
    {
        Name: "Noelani",
        Email: "ipsum@mollis.edu",
        Date: "07/30/2020",
        Country: "Guernsey",
        "Pin code": "9999",
    },
    {
        Name: "Buckminster",
        Email: "nec.malesuada.ut@mi.com",
        Date: "09/26/2021",
        Country: "Mozambique",
        "Pin code": "7900",
    },
    {
        Name: "Boris",
        Email: "nunc@feugiat.com",
        Date: "08/22/2020",
        Country: "Uruguay",
        "Pin code": "6252",
    },
    {
        Name: "Adele",
        Email: "enim.nisl.elementum@liberoduinec.ca",
        Date: "01/15/2022",
        Country: "Dominica",
        "Pin code": "5532",
    },
    {
        Name: "Carson",
        Email: "amet.ultricies.sem@sitametconsectetuer.ca",
        Date: "10/08/2021",
        Country: "Latvia",
        "Pin code": "9457",
    },
    {
        Name: "Victoria",
        Email: "eu@velarcu.edu",
        Date: "06/02/2020",
        Country: "Denmark",
        "Pin code": "6523",
    },
    {
        Name: "Caldwell",
        Email: "Donec.porttitor@erosnonenim.com",
        Date: "07/09/2020",
        Country: "Spain",
        "Pin code": "3224",
    },
    {
        Name: "Xavier",
        Email: "libero.Donec@quamPellentesque.ca",
        Date: "09/21/2021",
        Country: "Equatorial Guinea",
        "Pin code": "2532",
    },
    {
        Name: "Jessica",
        Email: "feugiat@commodo.com",
        Date: "11/19/2021",
        Country: "Jamaica",
        "Pin code": "7387",
    },
    {
        Name: "Hayes",
        Email: "varius.orci@maurissagittisplacerat.ca",
        Date: "04/05/2020",
        Country: "Holy See (Vatican City State)",
        "Pin code": "9061",
    },
    {
        Name: "Rajah",
        Email: "Donec.tempor@idenimCurabitur.com",
        Date: "11/27/2021",
        Country: "Eritrea",
        "Pin code": "5860",
    },
    {
        Name: "Jolene",
        Email: "nunc.In.at@Proindolor.ca",
        Date: "01/13/2021",
        Country: "Chile",
        "Pin code": "8332",
    },
    {
        Name: "Gabriel",
        Email: "tincidunt@a.net",
        Date: "09/09/2020",
        Country: "Swaziland",
        "Pin code": "1485",
    },
    {
        Name: "Jakeem",
        Email: "semper.et@a.ca",
        Date: "07/18/2021",
        Country: "Trinidad and Tobago",
        "Pin code": "1167",
    },
    {
        Name: "Phillip",
        Email: "massa@massa.net",
        Date: "04/20/2020",
        Country: "Macedonia",
        "Pin code": "9308",
    },
    {
        Name: "Clio",
        Email: "fringilla.purus.mauris@dolorsit.edu",
        Date: "06/18/2021",
        Country: "Czech Republic",
        "Pin code": "3281",
    },
    {
        Name: "Shelly",
        Email: "arcu@ligula.co.uk",
        Date: "10/30/2021",
        Country: "Syria",
        "Pin code": "9075",
    },
    {
        Name: "Erica",
        Email: "pede.et@tristiquenequevenenatis.org",
        Date: "12/14/2020",
        Country: "Switzerland",
        "Pin code": "9701",
    },
    {
        Name: "Oleg",
        Email: "molestie@sed.net",
        Date: "06/10/2020",
        Country: "Finland",
        "Pin code": "4452",
    },
    {
        Name: "Nolan",
        Email: "sollicitudin@neccursus.ca",
        Date: "06/17/2021",
        Country: "Estonia",
        "Pin code": "1222",
    },
    {
        Name: "Gwendolyn",
        Email: "magna@massa.edu",
        Date: "11/10/2021",
        Country: "Sierra Leone",
        "Pin code": "4690",
    },
    {
        Name: "Wesley",
        Email: "a.dui@penatibusetmagnis.co.uk",
        Date: "03/17/2022",
        Country: "Guinea",
        "Pin code": "9623",
    },
    {
        Name: "Vaughan",
        Email: "massa.Integer@Maurisvelturpis.net",
        Date: "05/22/2021",
        Country: "Botswana",
        "Pin code": "3542",
    },
    {
        Name: "Alea",
        Email: "facilisis.facilisis@nequetellusimperdiet.net",
        Date: "12/13/2020",
        Country: "Philippines",
        "Pin code": "1680",
    },
    {
        Name: "Cody",
        Email: "Suspendisse.eleifend.Cras@elementumlorem.com",
        Date: "11/23/2020",
        Country: "Bouvet Island",
        "Pin code": "4050",
    },
    {
        Name: "Nathan",
        Email: "parturient.montes@auctorveliteget.ca",
        Date: "12/17/2021",
        Country: "Macedonia",
        "Pin code": "6673",
    },
    {
        Name: "Brooke",
        Email: "purus@Integer.net",
        Date: "03/28/2022",
        Country: "Rwanda",
        "Pin code": "8730",
    },
    {
        Name: "Kaseem",
        Email: "at.risus@lacinia.com",
        Date: "01/15/2022",
        Country: "French Polynesia",
        "Pin code": "9079",
    },
    {
        Name: "Hector",
        Email: "ultricies.adipiscing.enim@loremloremluctus.com",
        Date: "06/18/2021",
        Country: "Tunisia",
        "Pin code": "6355",
    },
    {
        Name: "Blair",
        Email: "odio.Phasellus@consequatnec.org",
        Date: "11/16/2021",
        Country: "Djibouti",
        "Pin code": "1760",
    },
    {
        Name: "Jane",
        Email: "adipiscing.elit.Aliquam@mollisPhasellus.edu",
        Date: "11/04/2021",
        Country: "Saint Vincent and The Grenadines",
        "Pin code": "2325",
    },
    {
        Name: "Teagan",
        Email: "velit.Cras.lorem@a.net",
        Date: "01/20/2021",
        Country: "Mayotte",
        "Pin code": "7432",
    },
    {
        Name: "Deborah",
        Email: "sit.amet.lorem@molestieSed.co.uk",
        Date: "04/03/2021",
        Country: "Rwanda",
        "Pin code": "8594",
    },
    {
        Name: "Evangeline",
        Email: "magna.a.neque@Proin.ca",
        Date: "03/08/2021",
        Country: "Belgium",
        "Pin code": "6821",
    },
    {
        Name: "Garth",
        Email: "egestas.blandit@etrisus.edu",
        Date: "11/26/2020",
        Country: "Ireland",
        "Pin code": "6336",
    },
    {
        Name: "Vincent",
        Email: "parturient@ante.com",
        Date: "07/09/2021",
        Country: "Sweden",
        "Pin code": "1708",
    },
    {
        Name: "Maxine",
        Email: "lacus.vestibulum.lorem@adipiscingligulaAenean.org",
        Date: "06/06/2021",
        Country: "Croatia",
        "Pin code": "5929",
    },
    {
        Name: "Nevada",
        Email: "purus.Duis.elementum@maurissagittis.org",
        Date: "07/11/2020",
        Country: "Cayman Islands",
        "Pin code": "2200",
    },
    {
        Name: "Lillian",
        Email: "Integer@vulputatemauris.ca",
        Date: "04/21/2020",
        Country: "Saint Martin",
        "Pin code": "2425",
    },
    {
        Name: "Palmer",
        Email: "vitae@Cras.ca",
        Date: "09/04/2020",
        Country: "Cyprus",
        "Pin code": "1958",
    },
    {
        Name: "Levi",
        Email: "aliquam.iaculis@auctornunc.net",
        Date: "06/12/2020",
        Country: "El Salvador",
        "Pin code": "5285",
    },
    {
        Name: "Merritt",
        Email: "lectus.justo@arcu.net",
        Date: "12/19/2021",
        Country: "Luxembourg",
        "Pin code": "7891",
    },
    {
        Name: "Akeem",
        Email: "Proin.velit@esttempor.edu",
        Date: "11/03/2020",
        Country: "Estonia",
        "Pin code": "8239",
    },
    {
        Name: "April",
        Email: "purus.ac.tellus@gravida.co.uk",
        Date: "07/10/2021",
        Country: "Timor-Leste",
        "Pin code": "1260",
    },
    {
        Name: "August",
        Email: "Sed@hendrerit.edu",
        Date: "09/10/2020",
        Country: "Philippines",
        "Pin code": "3488",
    },
    {
        Name: "Hammett",
        Email: "elit@blanditviverraDonec.edu",
        Date: "07/20/2021",
        Country: "Luxembourg",
        "Pin code": "5063",
    },
    {
        Name: "Brielle",
        Email: "arcu.Nunc.mauris@ultriciessemmagna.com",
        Date: "09/30/2021",
        Country: "Slovakia",
        "Pin code": "6020",
    },
    {
        Name: "Len",
        Email: "erat.volutpat.Nulla@Sedmalesuada.edu",
        Date: "05/06/2021",
        Country: "Faroe Islands",
        "Pin code": "5371",
    },
    {
        Name: "Graiden",
        Email: "Nulla@euelit.ca",
        Date: "08/18/2020",
        Country: "Iceland",
        "Pin code": "9940",
    },
    {
        Name: "Graham",
        Email: "vitae.sodales@egestasnuncsed.edu",
        Date: "06/17/2021",
        Country: "China",
        "Pin code": "8221",
    },
    {
        Name: "Jermaine",
        Email: "tincidunt.nunc@sodalespurus.net",
        Date: "03/24/2022",
        Country: "Viet Nam",
        "Pin code": "5373",
    },
    {
        Name: "Blake",
        Email: "Quisque.purus.sapien@magnatellus.edu",
        Date: "10/30/2021",
        Country: "Myanmar",
        "Pin code": "2172",
    },
    {
        Name: "Signe",
        Email: "dolor.dapibus@laoreetposuereenim.edu",
        Date: "03/25/2022",
        Country: "Mauritania",
        "Pin code": "8831",
    },
    {
        Name: "Pearl",
        Email: "ac.orci@leo.edu",
        Date: "05/14/2020",
        Country: "Morocco",
        "Pin code": "1123",
    },
    {
        Name: "Gannon",
        Email: "parturient.montes.nascetur@viverraMaecenasiaculis.ca",
        Date: "08/17/2021",
        Country: "Romania",
        "Pin code": "8253",
    },
    {
        Name: "Jack",
        Email: "vehicula.et@adipiscingelit.net",
        Date: "10/29/2020",
        Country: "British Indian Ocean Territory",
        "Pin code": "7540",
    },
    {
        Name: "Julian",
        Email: "ornare@lectusasollicitudin.com",
        Date: "12/15/2021",
        Country: "Bahrain",
        "Pin code": "4385",
    },
    {
        Name: "Wyatt",
        Email: "vitae.semper@ornare.org",
        Date: "01/11/2021",
        Country: "Nauru",
        "Pin code": "4667",
    },
    {
        Name: "Dakota",
        Email: "neque.In@vitaealiquameros.edu",
        Date: "11/08/2020",
        Country: "Kazakhstan",
        "Pin code": "9833",
    },
    {
        Name: "Amber",
        Email: "magna@Donecelementumlorem.ca",
        Date: "07/15/2021",
        Country: "Kenya",
        "Pin code": "2862",
    },
    {
        Name: "Regina",
        Email: "et.netus.et@arcu.edu",
        Date: "10/20/2020",
        Country: "Haiti",
        "Pin code": "6482",
    },
    {
        Name: "Howard",
        Email: "auctor.quis@ascelerisquesed.com",
        Date: "06/02/2020",
        Country: "Saint Barthélemy",
        "Pin code": "2213",
    },
    {
        Name: "Gavin",
        Email: "ut@Curabiturconsequatlectus.org",
        Date: "02/25/2021",
        Country: "Iceland",
        "Pin code": "4711",
    },
    {
        Name: "Rhona",
        Email: "elit.a.feugiat@antelectusconvallis.edu",
        Date: "01/09/2021",
        Country: "Pakistan",
        "Pin code": "2829",
    },
    {
        Name: "Iris",
        Email: "leo@magnaatortor.net",
        Date: "02/19/2021",
        Country: "South Sudan",
        "Pin code": "3709",
    },
    {
        Name: "Stuart",
        Email: "consequat@nunc.org",
        Date: "08/15/2020",
        Country: "Luxembourg",
        "Pin code": "3623",
    },
    {
        Name: "Zelda",
        Email: "ante.ipsum@sem.edu",
        Date: "07/03/2020",
        Country: "Indonesia",
        "Pin code": "1902",
    },
    {
        Name: "Hasad",
        Email: "in.hendrerit@eu.co.uk",
        Date: "11/21/2020",
        Country: "Guinea",
        "Pin code": "7568",
    },
    {
        Name: "Bethany",
        Email: "a.arcu@ligulaAenean.edu",
        Date: "03/10/2021",
        Country: "Chad",
        "Pin code": "7104",
    },
    {
        Name: "Paul",
        Email: "Nullam@odiotristique.ca",
        Date: "11/30/2020",
        Country: "Curaçao",
        "Pin code": "7962",
    },
    {
        Name: "Alexander",
        Email: "amet.ultricies@enimNuncut.co.uk",
        Date: "04/08/2021",
        Country: "Slovakia",
        "Pin code": "7367",
    },
    {
        Name: "Lysandra",
        Email: "ipsum@Morbi.edu",
        Date: "01/01/2021",
        Country: "Turkmenistan",
        "Pin code": "6368",
    },
    {
        Name: "Nayda",
        Email: "massa@Curabitur.net",
        Date: "05/07/2021",
        Country: "Uruguay",
        "Pin code": "3351",
    },
    {
        Name: "Barbara",
        Email: "dolor.nonummy@idlibero.ca",
        Date: "11/07/2021",
        Country: "Equatorial Guinea",
        "Pin code": "8042",
    },
    {
        Name: "Wayne",
        Email: "enim.mi.tempor@nasceturridiculusmus.org",
        Date: "02/16/2022",
        Country: "Guyana",
        "Pin code": "9703",
    },
    {
        Name: "Ruby",
        Email: "tincidunt.aliquam@idblandit.co.uk",
        Date: "12/29/2020",
        Country: "Micronesia",
        "Pin code": "6795",
    },
    {
        Name: "Sydney",
        Email: "egestas.a@risusMorbi.edu",
        Date: "04/13/2021",
        Country: "Côte D'Ivoire (Ivory Coast)",
        "Pin code": "2161",
    },
    {
        Name: "Steven",
        Email: "tincidunt.congue.turpis@ullamcorper.co.uk",
        Date: "11/20/2021",
        Country: "Belarus",
        "Pin code": "9285",
    },
    {
        Name: "Lareina",
        Email: "Aenean.sed.pede@nec.edu",
        Date: "03/31/2022",
        Country: "Bonaire, Sint Eustatius and Saba",
        "Pin code": "9763",
    },
    {
        Name: "Zelenia",
        Email: "ligula@pretiumnequeMorbi.com",
        Date: "04/14/2021",
        Country: "Bulgaria",
        "Pin code": "3400",
    },
    {
        Name: "Wilma",
        Email: "tempus.lorem@molestieorci.ca",
        Date: "05/29/2020",
        Country: "Solomon Islands",
        "Pin code": "2899",
    },
    {
        Name: "Basia",
        Email: "in.faucibus@sed.co.uk",
        Date: "09/19/2020",
        Country: "Kazakhstan",
        "Pin code": "1762",
    },
];
const createData = (sno, name, email, date, country, pincode) => {
    return { sno, name, email, date, country, pincode };
};

export const columns = [
    { id: "sno", label: "S.No", minWidth: "2em" },
    { id: "name", label: "Name", minWidth: "10em" },
    { id: "email", label: "Email", minWidth: "10em" },
    { id: "date", label: "Date", minWidth: "10em" },
    { id: "country", label: "Country", minWidth: "10em" },
    { id: "pincode", label: "Pin Code", minWidth: "10em" },
];

export const rows = data.map((elem, index) => {
    return createData(
        index + 1,
        elem.Name,
        elem.Email,
        elem.Date,
        elem.Country,
        elem["Pin code"]
    );
});
