name: Publish stories
on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Install and Build
              run: |
                  yarn 
                  yarn run predeploy
                  yarn run deploy-storybook

            - name: Deploy
            - uses: actions/labeler@v2
            with:
              repo-token: ${{ secrets.GITHUB_TOKEN }}
