name: Publish stories
on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Install and Build
              run: |
                  yarn 
                  yarn run predeploy
                  yarn run deploy-storybook

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@3.6.2
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: master # The branch the action should deploy to.
                  FOLDER: docs-build # The folder that the build-storybook script generates files.
                  CLEAN: true # Automatically remove deleted files from the deploy branch
                  TARGET_FOLDER: docs
